spring:
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 驱动类 跟mysql驱动类版本有关
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 跟mysql版本有关
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

logging:
  level:
    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mybatis-plus全局配置
  global-config:
    db-config:
      # mybatis-plus在分析根据mapper传递的泛型参数User时，会在分析出的表明user前缀加上t_
      table-prefix: t_
      # 全局统一配置主键的生成策略为自动递增
      id-type: auto
  # 扫描以下包中的类使用类型别名
  type-aliases-package: com.hao_xiao_zi.mybatisplus.pojo
