service:
  config:
#    ipAddress: 127.0.0.1
#    ip-address: 127.0.0.1
#    ip_address: 127.0.0.1
    IP-ADDRESS: 127.0.0.1
    port: 0127
    timeout: 22
    serviceTimeOut: 3
    dataSize: 1024MB

dataSource:
  driverclassname: com.mysql.cj.jdbc.Driver123
#  ??yml???????????0?0~7??,?????????????,???????????????????
  password: "0127"